Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.synced_folder "../playbooks/", "/vagrant/playbooks"

    config.vm.provision "ansible_local" do |ansible| #using ansible_local because of the Windows host
      ansible.verbose = "v"
      ansible.playbook = "/vagrant/playbooks/bootstrap.yml"
  end
end